### ISSUE TITLE
Filter out filetypes from buffer list

### ISSUE THREAD

**Issue by olimorris** [noib3/cokeline.nvim#11]
Sometimes I may get a rogue terminal or a filetype appear in my buffer list which I'd rather not see. In bufferline you can filter these out through a custom function. Is this something that can be done already in our beloved `cokeline`?

**Comment by olimorris** [comment]
I've added an `is_visible` property to the buffers. Let me know what you think.

**Comment by noib3** [comment]
I've just pushed 20d3e205f64b23b98a91cac1d72e953a1c3d46b7 which should solve this in a more general way.

The `<Plug>(cokeline-focus-prev)`, `<Plug>(cokeline-focus-next)`, `<Plug>(cokeline-switch-prev)` and `<Plug>(cokeline-switch-next)` mappings should all work even for filtered buffers.

 Let me know if you have any more problems.
