### ISSUE TITLE
option for never show tabline

### ISSUE THREAD

**Issue by CRAG666** [noib3/cokeline.nvim#14]
I only use the tabs when I have more 4 tabs open so when I try to set showtabline = 0, its complement keeps looking for them, I have already configured a map to do toggle

**Comment by CRAG666** [comment]
I just need the plugin to respect vim.o.showtabline=0

**Comment by noib3** [comment]
If you never want to see the bufferline then why are you using a bufferline plugin?

**Comment by CRAG666** [comment]
As I said, it is useful for me only when I have more than 4 tabs, in that case I have a keymap to do toggle

**Comment by noib3** [comment]
I'm sorry but I don't think providing a toggle would be of great utility to other users. I might change `hide_when_one_buffer = true` to something like `show_when_buffers_more_than = 1`. That way you could set it to `show_when_buffers_more_than = 4`.

**Comment by noib3** [comment]
I've added a new config option `show_if_buffers_are_at_least = int`. If you want to show the bufferline only when there 4 or more buffers open you could set it to `show_if_buffers_are_at_least = 4`.
