### ISSUE TITLE
max_line_width only for certain components

### ISSUE THREAD

**Issue by olimorris** [noib3/cokeline.nvim#17]
This is a potentially tricky issue to solve...

When I implement `max_line_width`, it quite correctly trims each buffer to the integer I set. Unfortunately I have a component which sticks a nice big red circle if the buffer has been modified and not saved. The `max_line_width` chops this off, as intended.

It would be great to be able to get `max_line_width` to ignore components which have a certain property like `ignore_truncate = true`, that way the filename of the buffer (which I do want truncated) is trimmed, but not my modified icon.

**Comment by noib3** [comment]
You can increase that component's priority to make sure it remains visible, for example

```lua
local nice_big_red_cirlce = {
  text = ..,
  hl = ..,
  truncation = {
    priority = 1,
  }
}
```
Check out the [line width constraints](https://github.com/noib3/cokeline.nvim#line-width-constraints-experimental) section of the README for more infos.

The `truncation` can also take a `direction = 'left' | 'right'` key to specify the direction from which a component is truncated. In my own config I set `direction = 'left'` for `buffer.filename` and `buffer.unique_prefix`.
