### ISSUE TITLE
Nvim freezes when creating a new tab while a no name buffer is open.

### ISSUE THREAD

**Issue by Ruthenic** [noib3/cokeline.nvim#18]
Whenever I launch nvim with no arguments and attempt to IE run `:PackerSync`, nvim freezes and spikes to 100% CPU usage. I *think* this is a similar bug to [bufferline.nvim#40](https://github.com/akinsho/bufferline.nvim/issues/40) (considering I can reproduce it under the same circumstances, just replace bufferline with cokeline).

thanks for the great plugin!

**Comment by noib3** [comment]
Hi, I can reproduce the issue. No idea what's causing this at the moment. Will look into it tomorrow.

**Comment by noib3** [comment]
I just pushed a commit that should fix this. Could you test it?

**Comment by Ruthenic** [comment]
Sorry for the late test, but I can confirm that it works!
