### ISSUE TITLE
Insert new buffer after current one

### ISSUE THREAD

**Issue by andytsan** [noib3/cokeline.nvim#22]
Hi, just wondering if you will support inserting buffers immediately after the current open one?

This is something I use constantly from BarBar.nvim but is missing from any other bufferline plugins. I've asked @akinsho about it here as well: https://github.com/akinsho/bufferline.nvim/issues/232

**Comment by noib3** [comment]
Mh, I think my answer is similar to @akinsho's, altough the way we handle buffer order shouldn't make this too hard to implement.

I'll probably implement this feature in the (more or less) near future but it's low priority for now.

P.S. If by any chance you feel like taking a shot at this yourself, take a look at https://github.com/noib3/cokeline.nvim/blob/31bc6284db3813033413c2e39003c86165c7e895/lua/cokeline/buffers.lua#L131

This is the function responsible for collecting all the buffers and it's called everytime the bufferline changes.

It takes an `order` table, which is a list of the numbers of the all the opened buffers (i.e. what you see with `:ls` in the current order).

When a new buffer is added, we first collect all the "old" buffers, i.e. the buffers whose numbers were already present in the order table passed in, then all the "new" buffers. The new buffer list is given by all the old buffers **followed** by all the new ones.

To implement your feature the new buffer list would have to be given by all the old buffers **up to** the currently focused one, then all the new buffers, then all the old buffers from the focused one + 1 till the end.

**Comment by andytsan** [comment]
Thanks, that makes perfect sense. I will take a look.

**Comment by noib3** [comment]
It's now possible to open new buffers next to the current one by setting
```lua
require('cokeline').setup({
  -- ...
  buffers = {
    new_buffers_position = 'next' -- 'next' | 'last', default is 'last'
  }
  -- ..
})
```

**Comment by andytsan** [comment]
Amazing, this works perfectly thank you! I've now switched over to using cokeline full-time! What a great plugin!

**Comment by noib3** [comment]
> I've now switched over to using cokeline full-time! What a great plugin!

Thanks!

There still one caveat at the moment: if you open multiple buffers at the same time they will be added next to the current buffer but in the opposite order of what they should be. For example, let's say you have the buffers
```
a* | b
````
where the `*` indicates the currently focused buffer. If you open `c` and `d` at the same time (and in that order) you'd expect to end up with
```
a | c* | d | b
```
instead you end up with
```
a | d | c* | b
```
That still needs to be fixed.

**Comment by andytsan** [comment]
Understood. Yes this won't affect my workflow personally but I can see how it might be confusing to others.
