### ISSUE TITLE
Make default_hl accept functions

### ISSUE THREAD

**Issue by EtiamNullam** [noib3/cokeline.nvim#23]
It would be nice if it was possible to pass function as an alternative to string for `default_hl` similar to how its already possible in components. I managed to change background of buffer (in bufferline) that is modified and I believe currently the best way is to override background of every component like so:

```lua
components = {
  {
    text = function(buffer) return buffer.filename .. ' ' end,
    hl = {
      fg = function(buffer)
        return buffer.is_modified
          and get_hex('ErrorMsg', 'bg')
      end,
      bg = function(buffer)
        return buffer.is_modified
          and get_hex('ErrorMsg', 'fg')
      end,
    }
  },
}
```

When it would be more convenient to just do something like this in `default_hl`:

```lua
default_hl = {
  focused = {
    fg = function(buffer) -- seems like currently you can't provide a function here
      return buffer.is_modified
        and get_hex('ErrorMsg', 'bg')
        or get_hex('ColorColumn', 'bg')
    end,
    bg = function(buffer) -- seems like currently you can't provide a function here
      return buffer.is_modified
        and get_hex('ErrorMsg', 'bg')
        or get_hex('Normal', 'fg')
    end,
  },
},
```

Above example would make required config much smaller by reducing lots of repetition. I'm not sure about impact on performance but running it once per buffer instead once for every component in every buffer sounds better.

An alternative that I can imagine is to add `default_hl` group - `modified` that will provide default color for modified buffers:

```lua
default_hl = {
  modified = {
    fg = get_hex('ErrorMsg', 'bg'),
    bg = get_hex('ErrorMsg', 'fg'),
  },
},
```

Correct me if I'm doing something wrong or if there is already a way to do that. Maybe I'm just missing something.

NOTE: Highlight groups I've used in my examples might not look good for every colorscheme.

**Comment by noib3** [comment]
> Correct me if I'm doing something wrong or if there is already a way to do that.

You're not wrong, right now you can't pass functions to `default_hl` like you can for the components. I agree it makes sense to add that functionality. I'll add this sometime in the next few days.

**Comment by noib3** [comment]
@EtiamNullam You can now pass a function to the values in `default_hl`. Feel free to reopen if you have any questions.

**Comment by EtiamNullam** [comment]
I already found a different solution and I'm happy about it:

![image](https://user-images.githubusercontent.com/10875340/146462146-38205ab3-71f7-490a-b832-40028780697b.png)

For sure many others and me in future will make use of `default_hl` accepting functions. Thank you for plugin with such great performance and customization!

FYI I don't have the power to reopen :P
