### ISSUE TITLE
Focusing the next/previous buffer should wrap around

### ISSUE THREAD

**Issue by andytsan** [noib3/cokeline.nvim#25]
Would it be possible for `cokeline-focus-next`/`cokeline-focus-previous` to wrap around the list of buffers? E.g. if the last buffer in the list was currently selected, calling `cokeline-focus-next` would focus the first buffer.

**Comment by noib3** [comment]
Sure, just pass `cycle_prev_next_mappings = true` to the `"cokeline".setup` function.

**Comment by andytsan** [comment]
Yes thank you!
