### ISSUE TITLE
Could focus-prev focus-next ignore buffers from the filter

### ISSUE THREAD

**Issue by Irubataru** [noib3/cokeline.nvim#29]
Would it be possible for the `cokeline-focus-prev` and `cokeline-focus-next` commands to also skip the buffers ignored by the buffer filter in the config? In my case I ignore e.g. terminals as I have a utility terminal floating at the bottom, and when I cycle through my buffers I end up in that one although I don't expect it to.

Great plugin btw!

**Comment by noib3** [comment]
Mh, we could specify two different kind of filters, one to completely ignore buffers (what you are mentioning) and another one to simply skip rendering them while still being able to switch their order and focus them.

That way the `buffer` table in the config options would become
```lua
buffers = {
  filter_valid = function(buffer) .. end, -- totally ignore a buffer
  filter_visible = function(buffer) .. end, -- just don't render it (i.e. the current `filter`)
}
```

What do you think? Do you have a cleaner solution in mind?

**Comment by noib3** [comment]
I liked `filter_valid` and `filter_visible` because they map 1:1 to what those buffers are refered to internally, i.e. valid and visible respectively, but I'll consider that.

I'll ping you sometime in the next few days when I've implemented this.

**Comment by noib3** [comment]
@Irubataru I've just pushed this to master. I ended up choosing `filter_valid` and `filter_visible`. Feel free to reopen if you have any questions.

**Comment by Irubataru** [comment]
Works like a charm, thank you so much! :tada:
