### ISSUE TITLE
vim.diagnostic is nil

### ISSUE THREAD

**Issue by HallerPatrick** [noib3/cokeline.nvim#5]
Hey, 

I am running into some issues, while trying out this nice tab bar.

I am getting following error messages when starting up nvim:
`E5108: Error executing lua ...pack/packer/start/cokeline.nvim/lua/cokeline/buffers.lua:126: attempt to index field 'diagnostic' (a nil value)`

This happens when trying to check `if vim.diagnostic.get`. I also can't find this in the neovim docs. Do you mean `vim.lsp.diagnostic`? 

Greetings,
Patrick

**Comment by noib3** [comment]
What neovim version are you using? I'm running `v0.6.0-dev` where `vim.lsp.diagnostic` has been renamed to `vim.diagnostic`.

**Comment by HallerPatrick** [comment]
NVIM v0.6.0-dev+46-g682247b52

I can build the newest version of neovim and report again.

In your README it says neovim 0.5+, maybe change this to 0.6?

**Comment by HallerPatrick** [comment]
Okay, update to latest neovim and both both work `vim.diagnostic`and `vim.lsp.diagnostic`

**Comment by noib3** [comment]
I just pushed a possible fix for this. Could test for both `0.5.0` and `0.6.0`?

**Comment by HallerPatrick** [comment]
Seems to work now for both!

**Comment by noib3** [comment]
Great!
