### ISSUE TITLE
Handle sizing of components when there is not enough space

### ISSUE THREAD

**Issue by cseickel** [noib3/cokeline.nvim#6]
This issue is to discuss what to do when tabs are smaller than needed to display all of their components. This is very likely to happen if tabs are forced to fit the tab line rather than overflowing, but it can also happen if vertical tabs are implemented. 

There are two pieces of functionality that needs to be added:

1. A method of truncating strings that are too long.
2. A way of determining which components are hidden when under space pressure, and in what priority order.

For #1, I would recommend the configuration takes a function reference that would be called with the buffer info object, a number representing the available width, and the full list of buffers being displayed. We could provide three built-in functions for convenience:

a. left truncating: ....lename.txt
b. right truncating: filename....
c. mid truncating: filena...txt

The reason for also providing the full list of buffers as an argument is to allow for more advanced truncation that takes into account what else is displayed. For instance, you might want to intelligently truncate out the parts of the name that multiple files have in common.

For #2, it might be easiest to add a "min_line_width" option, and if the available width is smaller than that number then the component will be collapsed. It would also be nice to accept a function ref which is called with the buffer info and available width as arguments and return a boolean. I would personally use that option and determine whether or not the component is collapsed based on how much of the filename will be truncated.

Let me know what you think. I would be happy to contribute some work on all or part of this.

**Comment by noib3** [comment]
I've been thinking about this for a while and the more I do the more awkward edge cases I come up with.

I think the best option for now is to add support for equally sized lines with the most basic truncation algorithm, i.e. lines are shortened from right to left, and work up from there. This rendering option would be enabled with something like

```lua
require('cokeline').setup({
  rendering = {
    equally_sized_lines = true,
  },
  ...
})
```

> The reason for also providing the full list of buffers as an argument is to allow for more advanced truncation that takes into account what else is displayed

I think providing the `left`, `middle` and `right` options would be enough. Also, I'm afraid allowing user defined functions for component truncation might slow down the rendering of the bufferline.

> For #2, it might be easiest to add a "min_line_width" option, and if the available width is smaller than that number then the component will be collapsed.

I think it would have to be called `min_component_width`, since lines are made up of components and the problem of shrinking a line boils down to deciding which of its component to shrink first and how to shrink them.

This is an option, but we could also provide a `priority` key: if a line needs to be shortened we first cut off the component with the lowest priority to its `min_line_width`, we then do the same for the component with the second lowest priority, and so on until all the components are cutoff to their `min_line_width`. If this isn't enough we start removing components in order of increasing priority.

This approach is still far from ideal though. It could result in multiple components being cutoff on the same line, i.e. multiple ellipses being shown, which looks weird.

I should start working on this tomorrow on a new feature branch.

**Comment by noib3** [comment]
> On the subject of ellipsis, I was thinking about using another character that can convey the meaning while only taking up one space? Maybe that can be a configuration option? For example, I could use two periods instead of three, or the nerd font icon for horizontal dots (nf-mdi-dots_vertical) which is a single character.

Yeah sure we could add a configuration option for it, but that's low priority right now.

> Feel free to ping me when you have something working and I can help test it.

Will do.

**Comment by noib3** [comment]
> I should start working on this tomorrow..

Yeah about that, ... better late then never I guess.

So, I've been working on this for the past few days and I've introduced a few new config options. First off, the `setup` function now accepts a new `rendering` table with the following options:

```lua
require('cokeline').setup({
  ...
  rendering = {
    min_line_width = <int>,
    max_line_width = <int>,
  },
 ...
```
those options should be pretty self explanatory. At the moment setting `min_line_width` doesn't actually do anything, but it will in the near future. `max_line_width` should work but further testing is required.

Also, every `component` table now takes an optional `truncation` table of the form:
```lua
{
  ...
  truncation = {
    priority = <int>,
    direction = 'left' | 'right',
  }
}
```
the priority key is used to determine which component gets cut off first when under space pressure. The default value is the index of that component in the components table (i.e. the first component has default priority `1`, the second one `2`, and so on). The `direction` key is used to determine in which direction the component gets cut. `right` is the default.

To put it all together, this is my current config:

```lua
local get_hex = require('cokeline/utils').get_hex

local format = string.format
local keymap = vim.api.nvim_set_keymap

local nmaps = function(lhs, rhs)
  keymap('n', lhs, rhs, {silent = true})
end

nmaps('<S-Tab>', '<Plug>(cokeline-focus-prev)')
nmaps('<Tab>', '<Plug>(cokeline-focus-next)')
nmaps('<Leader>p', '<Plug>(cokeline-switch-prev)')
nmaps('<Leader>n', '<Plug>(cokeline-switch-next)')

for i = 1,9 do
  nmaps(format('<F%s>', i), format('<Plug>(cokeline-focus-%s)', i))
end

local saved_indicator = {
  text = '｜',
  hl = {
    fg = function(buffer)
      return
        buffer.is_modified
        and vim.g.terminal_color_3 -- yellow
         or vim.g.terminal_color_2 -- green
    end
  },
}

local devicon = {
  text = function(buffer) return buffer.devicon.icon .. ' ' end,
  hl = {
    fg = function(buffer) return buffer.devicon.color end,
  },
}

local index = {
  text = function(buffer) return buffer.index .. ': ' end,
  hl = {
    fg = function(buffer)
      return
        buffer.lsp.errors ~= 0
        and vim.g.terminal_color_1
         or nil
    end,
  },
}

local unique_prefix = {
  text = function(buffer) return buffer.unique_prefix end,
  hl = {
    fg = get_hex('Comment', 'fg'),
    style = 'italic',
  },
  truncation = {
    priority = 6,
    direction = 'left',
  },
}

local filename = {
  text = function(buffer) return buffer.filename end,
  hl = {
    fg = function(buffer)
      if buffer.lsp.errors ~= 0 then
        return vim.g.terminal_color_1
      end
      if buffer.lsp.warnings ~= 0 then
        return vim.g.terminal_color_3
      end
      return nil
    end,
    style = function(buffer)
      local style
      if buffer.is_focused then
        style = 'bold'
      end
      if buffer.lsp.errors ~= 0 then
        if style then
          style = style .. ',underline'
        else
          style = 'underline'
        end
      end
      return style
    end,
  },
  truncation = {
    priority = 5,
    direction = 'left',
  },
}

local space = {
  text = ' ',
  truncation = {
    priority = 4,
  }
}

require('cokeline').setup({
  hide_when_one_buffer = true,

  rendering = {
    min_line_width = 0,
    max_line_width = 25,
  },

  buffers = {
    filter = function(buffer)
      return buffer.type ~= 'terminal'
    end,
  },

  default_hl = {
    focused = {
      fg = get_hex('Normal', 'fg'),
      bg = get_hex('ColorColumn', 'bg'),
    },
    unfocused = {
      fg = get_hex('Comment', 'fg'),
      bg = get_hex('ColorColumn', 'bg'),
    },
  },

  components = {
    saved_indicator,
    devicon,
    index,
    unique_prefix,
    filename,
    space,
  },
})
```

Which looks like this

![2021-11-05_12-25](https://user-images.githubusercontent.com/59321248/140503554-d0f28e94-f772-40b9-9a7f-8da212dc64dc.png)


Feel free to test and play around with the new options. As always, any feedback is welcome.

**Comment by noib3** [comment]
I will close this for now. Feel free to reopen it if you feel like more work needs to be done.

**Comment by cseickel** [comment]
Hey @noib3, this looks like great work. Sorry I haven't kept up with this, but I ended up meeting my needs by modifying nvim-tree to show open buffers. I think that is the way to go to meet my original goal of having vertical tabs for my buffers.
