### ISSUE TITLE
My config

### ISSUE THREAD

**Issue by olimorris** [noib3/cokeline.nvim#8]
Thought I'd share my config as in about 10 mins I've got this looking exactly how I wanted.  `bufferline` was always a touch too opinionated for myself. My general principle with theming is "if I don't need to see something, it shouldn't be a visual burden". This is just perfect and I love the power.

## My config
![Screen Shot 2021-10-04 at 20 13 27](https://user-images.githubusercontent.com/9512444/135910562-fb499493-1442-4173-8003-e9aed03b2063.gif)

To enable the theme change, I load in my theme's colors and with a colorscheme autocommand, refresh `cokeline` on any change. I have also added in a modified button.

  <details>
  <summary>Click to see configuration</summary>

```lua
local M = {}

function M.setup()
	local present, cokeline = pcall(require, "cokeline")
	if not present then
		return
	end

	local colors = require("colors").get()

	cokeline.setup({

		hide_when_one_buffer = true,
		cycle_prev_next_mappings = true,

		default_hl = {
			focused = {
				fg = colors.purple,
				bg = "NONE",
				style = "bold",
			},
			unfocused = {
				fg = colors.gray,
				bg = "NONE",
			},
		},

		components = {
			{
				text = function(buffer)
					return buffer.index ~= 1 and "  "
				end,
			},
			{
				text = function(buffer)
					return buffer.index .. ": "
				end,
				hl = {
					style = function(buffer)
						return buffer.is_focused and "bold" or nil
					end,
				},
			},
			{
				text = function(buffer)
					return buffer.unique_prefix
				end,
				hl = {
					fg = function(buffer)
						return buffer.is_focused and colors.purple or colors.gray
					end,
					style = "italic",
				},
			},
			{
				text = function(buffer)
					return buffer.filename .. " "
				end,
				hl = {
					style = function(buffer)
						return buffer.is_focused and "bold" or nil
					end,
				},
			},
			{
				text = function(buffer)
					return buffer.is_modified and " ●"
				end,
				hl = {
					fg = function(buffer)
						return buffer.is_focused and colors.red
					end,
				},
			},
			{
				text = "  ",
			},
		},
	})
end

return M

```
  </details>

When I first used `cokeline` I was surprised that `cycle_prev_next_mappings = true` was not the default option. It's something I am so used to with all other buffer plugins.

Btw...happy to move this to a "Users Config" thread

**Comment by olimorris** [comment]
@noib3 -  Closing the issue and tagging you for thanks

**Comment by noib3** [comment]
Glad you like it!

> Btw...happy to move this to a "Users Config" thread

We could probably add a section to the README showing off various configurations. I'll probably do that later/tomorrow, or feel free to send another PR and I'll merge it.
